pipeline {
	agent any
    stages {
        stage('Build on k8 ') {
            steps {           
                        sh 'pwd'
                        sh 'cp -R CD-Job/helm/* .'
		                sh 'ls -ltr'
                        sh 'pwd'
                        sh '/usr/local/bin/helm upgrade --install petclinic-app petclinic  --set image.repository=registry.hub.docker.com/mohamedbenaantar/petclinic --set image.tag=1'
              			
            }           
        }
    }
}
$ helm install my-release autoscaler/cluster-autoscaler \
    --set autoDiscovery.clusterName=cluster-02 \
    --set awsRegion=us-east-1